### ISSUE TITLE
Can't use callback which is nested inside initializer class

### ISSUE THREAD

**Issue by bimargulies** [mock-server/mockserver#189]
I wrote:

```
public class MockWorkerInitializer implements ExpectationInitializer {
    public static class SentencesCallback implements ExpectationCallback {
    // ...
    }
    ...
}
```

And then used SentencesCallback.class.getName() as the callback class name.

And I got ...

[ERROR] ClassNotFoundException - while trying to instantiate ExceptionCallback class "com.basistech.ws.itest.MockWorkerInitializer$SentencesCallback"
java.lang.ClassNotFoundException: com.basistech.ws.itest.MockWorkerInitializer$SentencesCallback

If the initializer is in the classpath, how can the callback inside of it not be?

**Comment by jamesdbloom** [comment]
How are you running the MockServer?  It looks like you class `com.basistech.ws.itest.MockWorkerInitializer` has not been added to the classpath.  The maven plugin must be started during the process-test-classes to ensure that the initialization class has been compiled from either `src/main/java` or `src/test/java` locations.  In addition the initializer can only be used with `start` and `run` but not for `runForked` goals.  The support for initializers will be extended but will always required the initializer class to have been added to the classpath for the JVM that the MockServer is running on (see #190).

**Comment by bimargulies** [comment]
The initializer works fine! Only the callback fails. I have the standard
maven plugin setup.

**Comment by bimargulies** [comment]
To be clearer: I started by writing the POM config below, and then adding an Initializer class to src/test/java, and using ordinary expectations. It all works. Then I went to add a Callback to the expectations, and tried to use a static class inside my Initializer class. That's what's not working. And why must callbacks be a class name? Why not permit  a `Class<?>` or even just an instance?

```
 <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <serverPort>1080</serverPort>
                    <proxyPort>1090</proxyPort>
                    <logLevel>DEBUG</logLevel>
                    <initializationClass>com.basistech.ws.itest.MockWorkerInitializer</initializationClass>
                </configuration>
                <executions>
                    <execution>
                        <id>process-test-classes</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by jamesdbloom** [comment]
The reason callbacks currently must be a class name and not an instance or Class<?> is because in many situations the MockServer runs in a totally separate JVM as a result the callback must be serialised into JSON.  I am currently working on a more dynamic solution using WebSockets that will allow instance methods (or closures) to be used as a callback, see #120.  An initial basic PoC has been done for this story but there is still much more work to do on this.

**Comment by jamesdbloom** [comment]
For the callback to work it must be able to be loaded as follows:

```java
Class.forName(httpCallback.getCallbackClass())
```

and must also pass the following test:

```java
ExpectationCallback.class.isAssignableFrom(expectationCallbackClass)
```

If you pass both of these conditions it should work correctly.

I'm happy to looking into this more and add some extra tests for static inner class callbacks, but I would suspect if you want to get this to work now I would look at the exact syntax you need to get `Class.forName(...)` to work.

**Comment by arnauldvm** [comment]
I do have the same kind of issue.
Using the maven plugin, and I could not use any callback.
I've tried putting it in : src/main/java/..., src/test/java, or even nested in my InitializationClass.

I always get ClassNotFoundException for the callback. (Though InitializationClass is found without any problem!)

I don't really get why we could not provide the callback as a class object (or even an instance)...
I have the impression it would be much more robust,

**Comment by 3791** [comment]
I understand what the likely issue is with the Maven plugin and the callback class. The key issue is that Maven segregates the classpath between different plugins and the source code (production or test). As a result it's hard for MockServer to find the callback class. This is potentially fixable in two ways:

1. I'll see if I can further tweak the way Maven loads the classpath for the plugin to fix the immediate issue. This may not be easy but I'll see what I can do.

2. Switch away from using callback classes to callback objects and closures. This is definitely achievable once the work on introducing web-sockets has been completed. This is already on the backlog and I have implemented part of the solution already. However, this is probably a bigger piece of work to do cleanly and reliably so I should try the first approach above before completing this implementation.

**Comment by jamesdbloom** [comment]
I understand what the likely issue is with the Maven plugin and the callback class. The key issue is that Maven segregates the classpath between different plugins and the source code (production or test). As a result it's hard for MockServer to find the callback class. This is potentially fixable in two ways:

1. I'll see if I can further tweak the way Maven loads the classpath for the plugin to fix the immediate issue. This may not be easy but I'll see what I can do.

2. Switch away from using callback classes to callback objects and closures. This is definitely achievable once the work on introducing web-sockets has been completed. This is already on the backlog and I have implemented part of the solution already. However, this is probably a bigger piece of work to do cleanly and reliably so I should try the first approach above before completing this implementation.

**Comment by nycjoker** [comment]
Any updates on this issue being resolved?

**Comment by seaward** [comment]
I'm trying 5.11.1, this issue still happens.

**Comment by jamesdbloom** [comment]
This is now fixed in the SNAPSHOT https://mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by nsyamalacue** [comment]
Hi @jamesdbloom 
I'm still seeing this issue with below maven configuration.

 <plugin>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-maven-plugin</artifactId>
                <version>5.14.0</version>
                <configuration>
                    <serverPort>1080</serverPort>
                    <logLevel>DEBUG</logLevel>
                    <initializationClass>com.example.mockserver.springboot.MockExpectationInitializer
                    </initializationClass>
                </configuration>
                <executions>
                    <execution>
                        <id>process-test-classes</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
</plugin>
