### ISSUE TITLE
400 response creating expectation with json array response body

### ISSUE THREAD

**Issue by madkin10** [mock-server/mockserver#713]
**Describe the issue**
Getting a 400 error response from the API while creating an expectation with a json array response body. The following exception is raised: `for field "/httpResponse/body" a plain string, JSON object or one of the following example bodies must be specified` The API should accept an array as a valid body and assume it is JSON as an array is a valid json body.

**What you are trying to do**
I am trying to mock some basic requests to support my cucumber test suite using a ruby wrapper against the rest API.

**MockServer version**
`mockserver/mockserver:mockserver-5.8.0`

**To Reproduce**
I created an example repo to recreate the issue: https://github.com/madkin10/mockserver-issue
- Clone the repo
- Ensure it is pointing at your instance of mockserver
- `bundle install`
- `ruby mock_server.rb`

1. How you are running MockServer (i.e maven plugin, docker, etc)
- Kubernetes helm chart
2. Code you used to create expectations
https://github.com/madkin10/mockserver-issue
3. What error you saw
`for field "/httpResponse/body" a plain string, JSON object or one of the following example bodies must be specified`

**Expected behaviour**
I would expect this request to get successfully registered as a json type.

**MockServer Log**
```
2020-01-10 19:15:24  org.mockserver.log.MockServerEventLog  SEVERE  exception processing: 

	{
	  "method" : "PUT",
	  "path" : "/foo",
	  "headers" : {
	    "Host" : [ "localhost" ],
	    "X-Request-ID" : [ "a1cb99178aa127132ecfe47f5fc056e2" ],
	    "X-Real-IP" : [ "127.0.0.1" ],
	    "X-Forwarded-For" : [ "127.0.0.1" ],
	    "X-Forwarded-Host" : [ "localhost" ],
	    "X-Forwarded-Port" : [ "1080" ],
	    "X-Forwarded-Proto" : [ "http" ],
	    "X-Scheme" : [ "https" ],
	    "X-Original-Forwarded-For" : [ "127.0.0.1" ],
	    "Content-Length" : [ "180" ],
	    "Accept" : [ "*/*" ],
	    "Accept-Encoding" : [ "gzip;q=1.0,deflate;q=0.6,identity;q=0.3" ],
	    "Content-Type" : [ "application/x-www-form-urlencoded" ],
	    "User-Agent" : [ "rest-client/2.1.0 (darwin19.2.0 x86_64) ruby/2.5.3p105" ]
	  },
	  "keepAlive" : true,
	  "secure" : false,
	  "body" : {
	    "type" : "STRING",
	    "string" : "{\"httpRequest\":{\"method\":\"GET\",\"path\":\"/foo\"},\"httpResponse\":{\"statusCode\":200,\"headers\":{\"Content-Type\":[\"application/json; charset=utf-8\"]},\"body\":[{\"foo\":\"bar\"},{\"bar\":\"foo\"}]}}",
	    "contentType" : "application/x-www-form-urlencoded"
	  }
	}

 error: 

	1 error:
	 - for field "/httpResponse/body" a plain string, JSON object or one of the following example bodies must be specified 
	   {
	     "type": "BINARY",
	     "base64Bytes": "",
	     "contentType": ""
	   }, 
	   {
	     "type": "JSON",
	     "json": "",
	     "contentType": ""
	   },
	   {
	     "type": "PARAMETERS",
	     "parameters": {"name": "value"}
	   },
	   {
	     "type": "STRING",
	     "string": ""
	   },
	   {
	     "type": "XML",
	     "xml": "",
	     "contentType": ""
	   }
```

**Comment by jamesdbloom** [comment]
This response is because current MockServer doesn't support a JSON array as a response body using the raw JSON format, instead, if you use the following format you can specify a JSON array:

```javascript
{
  "type": "JSON",
  "json": "",
  "contentType": ""
}
```
I have now added support for JSON arrays with the raw JSON format and deployed this to the latest SNAPSHOT version.  The next RELEASE version will contain this fix, likely released in the next few weeks.

**Comment by jamesdbloom** [comment]
To use the SNAPSHOT version see: http://mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by madkin10** [comment]
Thanks for the quick response 👍

**Comment by busches** [comment]
We're still seeing this issue using the latest docker snapshot and the `MOCKSERVER_INITIALIZATION_JSON_PATH` option.

We've tried both of the following:

```
[
  ...
  "httpResponse": {
    "body": {
      "moo": []
    }
]
```
And 
```
[
  ...
  "httpResponse": {
    "body": {
	  "type": "JSON",
	  "json": {
     	 "moo": []
      }	
    }
]
```

The server always returns an empty object back.
If we add another property to the response, that gets returned but the `moo` property with the empty array is always ignored.

**Comment by jamesdbloom** [comment]
I think this only what gets printed in the logs but I’ll double check. I think I’ll now how to resolve this as it’s caused the Jackson configuration.

**Comment by busches** [comment]
> I think this only what gets printed in the logs but I’ll double check. I think I’ll now how to resolve this as it’s caused the Jackson configuration.

It's not returning the `moo` property at all, as I'm attempting to deserialize that value and it's failing for being `null`. Can confirm via postman as well that nothing is returned.

**Comment by jamesdbloom** [comment]
Yes, your correct I have found the cause and now fixed it and added tests.

I am currently running the SNAPSHOT deploy build so in the next 20 minutes you should be able to retest and it should be working.  I'll be doing a new release very soon I just need to update the documentation for several new features around TLS before I do the next release.

**Comment by busches** [comment]
We pulled the lastest docker snapshot and we're still not getting anything back in our response, confirmed via postman and it's own logs. I can create a reproducible repo for you if you like?

**Comment by jamesdbloom** [comment]
Let me manually re-run the docker SNAPSHOT build because I suspect the latest docker SNAPSHOT (built automatically by docker inc.) contains a slightly older SNAPSHOT release from yesterday.

**Comment by jamesdbloom** [comment]
Yes the latest SNAPSHOT with the fix is dated 2020-01-31 06:53:38.0
But the docker SNAPSHOT build ran at 2020-01-31 06:35:24 so it just missed the latest SNAPSHOT in Sonatype repository.  However. I ran the build again and it didn't seem to have the fix but my local SNAPSHOT version does.  I'm running the SNAPSHOT build again to push a new SNAPSHOT to Sonatype then I'll run the Docker build again.

**Comment by jamesdbloom** [comment]
This is now resolved as follows:

```bash
$ docker pull mockserver/mockserver:mockserver-snapshot
mockserver-snapshot: Pulling from mockserver/mockserver
e7c96db7181b: Already exists 
f910a506b6cb: Already exists 
c2274a1a0e27: Already exists 
f84476cb6dc8: Pull complete 
18058af67837: Pull complete 
00b58a421fc7: Pull complete 
0c4c74a4e918: Pull complete 
ed87a665d0b8: Pull complete 
Digest: sha256:48bc441f93ad0ab3759925e9697baa23da796c893cee00ea5c1ed14875a7440d
Status: Downloaded newer image for mockserver/mockserver:mockserver-snapshot
docker.io/mockserver/mockserver:mockserver-snapshot

$ docker run --rm -p 1080:1080 mockserver/mockserver:mockserver-snapshot

java -XX:+UseContainerSupport -XX:MaxRAMPercentage=90.0  -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 1080 -logLevel INFO &

2020-01-31 16:47:22  org.mockserver.cli.Main  INFO  logger level is INFO, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties' 
2020-01-31 16:47:22  org.mockserver.log.MockServerEventLog  INFO  started on port: 1080 
2020-01-31 16:47:30  org.mockserver.log.MockServerEventLog  INFO  creating expectation:

	{
	  "id" : "c6b10c9b-7855-429e-a935-c7c567735d38",
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/simple"
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "body" : {
	      "type" : "JSON",
	      "json" : "{\"moo\":[]}"
	    }
	  }
	}
 
```

**Comment by busches** [comment]
Can confirm it works, thanks for the quick fix. Do you know when you'll tag
the next release? Rather rely on a tagged version to than snapshot and have
something break in the future we we forget we're still on snapshot.

**Comment by jamesdbloom** [comment]
I expect to do a release in the next week or so

**Comment by hertzcodes** [comment]
Hi. I have a question 

I think I have the same issue with json.

curl -v -X PUT "http://localhost:1080/mockserver/expectation" \
  -H 'Content-Type: application/json' \
  -d '{
    "httpRequest": {
      "path": "/v1/driver/geo-info",
      "method": "GET",
      "queryStringParameters": {
        "ids": ["1"],
        "enhanced": ["false"]
      },
      "headers": {
        "Content-Type": ["application/x-www-form-urlencoded"]
      }
    },
    "httpResponse": {
      "statusCode": 200,
      "headers": {
        "Content-Type": ["application/json"]
      },
      "body": {
        "type": "JSON",
        "value": {
          "status": 200,
          "data": [
            {
              "id": 1,
              "lat": 3,
              "lng": 3,
              "bearing": 1,
              "direction": [3, 3],
              "accuracy": 1.5
            }
          ]
        }
      }
    }
  }'

this is the request im sending but the body I want is empty. @jamesdbloom
