### ISSUE TITLE
mockserver.disableSystemOut=true disables all log messages

### ISSUE THREAD

**Issue by pnsantos** [mock-server/mockserver#747]
**Describe the issue**

Not really sure if expected behaviour, but the `mockserver.disableSystemOut` property, when set to `true`, seems to completely disable all logging.

**What you are trying to do**

I'm running `mockserver-netty-5.9.0-jar-with-dependencies.jar` in a docker image. 
I've added `log4j2` dependencies to the classpath and am using a log4j2 config to write logs to a file.
When mock server is run, log4j2 is configured as the [JDK logging adapter](https://logging.apache.org/log4j/2.x/log4j-jul/index.html)

**MockServer version**
5.9.0

**To Reproduce**
As I mentioned, I'm packaging `mockserver-netty-5.9.0-jar-with-dependencies.jar` (renamed to  into `mockserver.jar`) into a docker image.

My run commands is:
```
exec java -cp 'mockserver.jar:lib/*' \
    "${jvm_options[@]}" \
    "${system_properties[@]}" \
    org.mockserver.cli.Main \
    -serverPort $SERVER_PORT \
    -logLevel "$LOG_LEVEL"
```
In `lib/` I have:
```
log4j-api-2.13.1.jar
log4j-core-2.13.1.jar
log4j-jul-2.13.1.jar
```
Using the following JVM options:
```
-XX:+UseG1GC
-XX:+UseStringDeduplication
-XX:+DisableExplicitGC
-XX:+UseBiasedLocking
-Xms128m
-Xmx256m
```
and the following system properties:
```
mockserver.livenessHttpGetPath=/health/alive
log4j.configurationFile=config/log4j2.xml
java.util.logging.manager=org.apache.logging.log4j.jul.LogManager
```

The `config/log4j2.xml` is configured to write logs to file.

If I include `mockserver.disableSystemOut=true` then I get no logs (no matter the `LOG_LEVEL`).

If I remove it then I get logs as expected.

**Expected behaviour**

I would expect `disableSystemOut` to only disable `System.out` messages and have no effect on JDK log messages.

**Comment by jamesdbloom** [comment]
This is now fixed and is currently being deployed into the SNAPSHOT version, it'll be in the next RELEASE version.

**Comment by gonits** [comment]
@jamesdbloom  I am using mock server versiob : 5.11.1

But this issue is still there in the version I am using.
Whenever I disable SystemOut property using: -Dmockserver.disableSystemOut=true,
all the logs are disabled and a blank .log file is created.

Once I change the SystemOut configuration to Dmockserver.disableSystemOut=false, I start getting all the logs.

Can you please confirm if this issue was fixed or still a bug?

What setting would you recommend to disable just the syslogs and not the JDK log messages?
